spring.application.name=MilestoneProject
logging.level.root=DEBUG
server.port=8080

#spring.datasource.username=root
#spring.datasource.password=YOUR_PASSWORD
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:flightdb;DB_CLOSE_ON_EXIT=FALSE

spring.datasource.url=jdbc:postgresql://dpg-d4njf2adbo4c73fjlfng-a.oregon-postgres.render.com/flightsdb_xt2e
spring.datasource.username=flightsdb_xt2e_user
spring.datasource.password=2Dar8z8V1hZyHSTPiSab0utVb1tKu19c

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect